[build]
  publish = "public"
  command = "yarn build-prod"
[build.environment]
  YARN_VERSION = "1.22.5"
  NETLIFY_USE_YARN = "true"
  NETLIFY_YARN_WORKSPACES = "true"
  YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"

