TALK_EXTRAS = {
    "79JCGZ": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Lightning Talks",
        "video_start_time": "",
        "youtube_url": None,
    },
    "7GPCCR": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Canceled: Gotta Go Fast! Using Asyncio for More Efficient Web Scraping",
        "video_start_time": "",
        "youtube_url": None,
    },
    "8LLX9Y": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Evolve or Die: How I Stopped Avoiding and Starting Loving Python Upgrades",
        "video_start_time": "",
        "youtube_url": None,
    },
    "8PZZLK": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Introducing Immortal Objects: Building Block Towards a Multi-core Python Runtime",
        "video_start_time": "",
        "youtube_url": None,
    },
    "8TRXAM": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Boosting Neuroimaging Analysis and Results Digestibility 🧠",
        "video_start_time": "",
        "youtube_url": None,
    },
    "8WZN9J": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "A Python Sequence (Un)Packing Primer",
        "video_start_time": "",
        "youtube_url": None,
    },
    "C7YYRN": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Boosting Python Numeric Computations with Dynamic C++ Integration",
        "video_start_time": "",
        "youtube_url": None,
    },
    "DCZDL9": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Canceled: Building Resilient Applications with Circuit Breakers and Retries Using FastAPI",
        "video_start_time": "",
        "youtube_url": None,
    },
    "DQNF8G": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Hot: Pathlib, Not: String Paths",
        "video_start_time": "",
        "youtube_url": None,
    },
    "DVJYEG": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Stress Less: Easy Database Load Testing Using Python and Locust",
        "video_start_time": "",
        "youtube_url": None,
    },
    "E8JAWJ": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Snakes & Ladders: A Gentle Introduction to Generators and Iterators",
        "video_start_time": "",
        "youtube_url": None,
    },
    "EDLLMH": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "What Django Deployment is Really About",
        "video_start_time": "",
        "youtube_url": None,
    },
    "EJSYK9": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Keynote",
        "video_start_time": "",
        "youtube_url": None,
    },
    "EWVQHG": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Validating Complex Types Using Pydantic",
        "video_start_time": "",
        "youtube_url": None,
    },
    "FAKV3H": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Keynote: Brains Are Beautiful Liars",
        "video_start_time": "",
        "youtube_url": None,
    },
    "FBZUBP": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Python <3 Rust",
        "video_start_time": "",
        "youtube_url": None,
    },
    "FJ97TP": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Serverless AI Inferencing Using Python and WebAssembly",
        "video_start_time": "",
        "youtube_url": None,
    },
    "HCM8XD": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Is Python Your TYPE of Programming Language? How to Use Static Typing in Python with Type Hints, MyPy and Pydantic",
        "video_start_time": "",
        "youtube_url": None,
    },
    "HJH7YH": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Technical Empathy",
        "video_start_time": "",
        "youtube_url": None,
    },
    "HPDBPB": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Data Science & Agile: Strategies for Working Together",
        "video_start_time": "",
        "youtube_url": None,
    },
    "KHNSQ3": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Keynote: Changelong",
        "video_start_time": "",
        "youtube_url": None,
    },
    "KNVA99": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Sunday Welcome",
        "video_start_time": "",
        "youtube_url": None,
    },
    "KSJSPY": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Efficient Path Planning for Search and Rescue Missions Using Neural Networks",
        "video_start_time": "",
        "youtube_url": None,
    },
    "LUKKXH": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "How to Do the Same Thing Over and Over Again and Yield Different Results",
        "video_start_time": "",
        "youtube_url": None,
    },
    "NC9JDX": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Python + Discord = Great Bots!",
        "video_start_time": "",
        "youtube_url": None,
    },
    "NZWEHD": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "So, I Got Some Code Working… Now How Do I Share It?!",
        "video_start_time": "",
        "youtube_url": None,
    },
    "P397LH": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Data Engineering: The World Between Worlds",
        "video_start_time": "",
        "youtube_url": None,
    },
    "PMMXMD": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Enhancing the JupyterLab Notebook to Overcome Bioinformatics Analysis Challenges with GiN",
        "video_start_time": "",
        "youtube_url": None,
    },
    "QE87TH": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Quantum Computing with Qiskit in Galaxy",
        "video_start_time": "",
        "youtube_url": None,
    },
    "QPUASH": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "A Confession of My Python Sins",
        "video_start_time": "",
        "youtube_url": None,
    },
    "UGTCE7": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Closing Remarks",
        "video_start_time": "",
        "youtube_url": None,
    },
    "VPKXVW": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Saturday Welcome",
        "video_start_time": "",
        "youtube_url": None,
    },
    "VWWTQF": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Mastering the Zen of Dev Experience: Kubernetes and the Art of Simplicity",
        "video_start_time": "",
        "youtube_url": None,
    },
    "WMJDDE": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Wagtail: The Python CMS Taking the World by Storm",
        "video_start_time": "",
        "youtube_url": None,
    },
    "WY9FAP": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "20 GOTO 10: How to Make Scrolling ASCII Art",
        "video_start_time": "",
        "youtube_url": None,
    },
    "XXQLZ3": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Asyncio by Example",
        "video_start_time": "",
        "youtube_url": None,
    },
    "Y8BHML": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Simplifying Python Web App Operations: Automating K8s Ops with Open Source",
        "video_start_time": "",
        "youtube_url": None,
    },
    "YAQZHH": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Signal Processing in Electrochemistry with Python: Applications to the US Opioids Crisis",
        "video_start_time": "",
        "youtube_url": None,
    },
    "YMAT93": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Building Vector-Symbolic Architectures with Python",
        "video_start_time": "",
        "youtube_url": None,
    },
    "YZMLAA": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Device Authorization Flow 101: Logging in From Input Constrained Devices",
        "video_start_time": "",
        "youtube_url": None,
    },
    "ZDN8QP": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "Zen Commandments",
        "video_start_time": "",
        "youtube_url": None,
    },
    "ZXHQKT": {
        "channel_id": "",
        "channel_name": "",
        "content_warnings": None,
        "title": "23, Python and Me: Using Machine Learning in Python to Analyze Consumer Genomics Data",
        "video_start_time": "",
        "youtube_url": None,
    },
}

BREAKS = {
    "SATREG": {
        "code": "SATREG",
        "title": "Registration Opens",
        "start_time": "2024-07-27T08:00:00-04:00",
        "end_time": "2024-07-27T09:00:00-04:00",
        "type": "Break",
    },
    "BREAK1": {
        "code": "BREAK2",
        "title": "Break",
        "start_time": "2024-07-27T10:00:00-04:00",
        "end_time": "2024-07-27T10:15:00-04:00",
        "type": "Break",
    },
    "BREAK2": {
        "code": "BREAK3",
        "title": "Break",
        "start_time": "2024-07-27T10:45:00-04:00",
        "end_time": "2024-07-27T11:00:00-04:00",
        "type": "Break",
    },
    "BREAK3": {
        "code": "BREAK4",
        "title": "Break",
        "start_time": "2024-07-27T11:30:00-04:00",
        "end_time": "2024-07-27T11:45:00-04:00",
        "type": "Break",
    },
    "SATLUN": {
        "code": "SATLUN",
        "title": "Lunch Break",
        "start_time": "2024-07-27T12:15:00-04:00",
        "end_time": "2024-07-27T14:00:00-04:00",
        "type": "Break",
    },
    "BREAK4": {
        "code": "BREAK5",
        "title": "Break",
        "start_time": "2024-07-27T14:45:00-04:00",
        "end_time": "2024-07-27T15:00:00-04:00",
        "type": "Break",
    },
    "OPEN1": {
        "code": "OPEN1",
        "title": "open time slot",
        "start_time": "2024-07-27T15:00:00-04:00",
        "end_time": "2024-07-27T15:30:00-04:00",
        "type": "Open",
        "room": "Cattleya",
    },
    "BREAK5": {
        "code": "BREAK6",
        "title": "Break",
        "start_time": "2024-07-27T15:30:00-04:00",
        "end_time": "2024-07-27T15:45:00-04:00",
        "type": "Break",
    },
    "SATCLOSE": {
        "code": "SATCLOSE",
        "title": "Conference Space Closes",
        "start_time": "2024-07-27T18:30:00-04:00",
        "end_time": "2024-07-27T19:00:00-04:00",
        "type": "Break",
    },
    "SUNREG": {
        "code": "SUNREG",
        "title": "Registration Opens",
        "start_time": "2024-07-28T11:30:00-04:00",
        "end_time": "2024-07-28T12:00:00-04:00",
        "type": "Break",
    },
    "BREAK6": {
        "code": "BREAK7",
        "title": "Break",
        "start_time": "2024-07-28T12:15:00-04:00",
        "end_time": "2024-07-28T12:30:00-04:00",
        "type": "Break",
    },
    "BREAK7": {
        "code": "BREAK8",
        "title": "Break",
        "start_time": "2024-07-28T13:00:00-04:00",
        "end_time": "2024-07-28T13:15:00-04:00",
        "type": "Break",
    },
    "BREAK8": {
        "code": "BREAK9",
        "title": "Break",
        "start_time": "2024-07-28T13:45:00-04:00",
        "end_time": "2024-07-28T14:00:00-04:00",
        "type": "Break",
    },
    "BREAK9": {
        "code": "BREAK10",
        "title": "Break",
        "start_time": "2024-07-28T14:30:00-04:00",
        "end_time": "2024-07-28T14:45:00-04:00",
        "type": "Break",
    },
    "BREAK10": {
        "code": "BREAK11",
        "title": "Break",
        "start_time": "2024-07-28T15:15:00-04:00",
        "end_time": "2024-07-28T15:30:00-04:00",
        "type": "Break",
    },
}
