TALK_EXTRAS = {
    "HNKFLC": {
        "title": "Intro to Unit Testing and Continuous Integration",
        "youtube_url": "https://youtu.be/4Fc_ptaKYEQ",
        "content_warnings": None,
        "video_start_time": "10:30:00",
        "channel_id": 1002092124352815265,
        "channel_name": "intro-to-unit-testing-and-continuous-integration",
    },
    "TUJLCE": {
        "title": "Doing Everything Data Without Leaving the Notebook: Programmatic Jupyter Notebooks",
        "youtube_url": "https://youtu.be/RrEwicdbolE",
        "content_warnings": None,
        "video_start_time": "12:45:40",
        "channel_id": None,
        "channel_name": None,
    },
    "9D9P88": {
        "title": "Break",
        "youtube_url": "",
        "content_warnings": None,
        "video_start_time": "12:00:00",
        "channel_id": None,
        "channel_name": None,
    },
    "QXZH39": {
        "title": "Run-JS: A New Library for Running JavaScript Modules in Python",
        "youtube_url": "https://youtu.be/m9gOaMBLkpk",
        "content_warnings": None,
        "video_start_time": "14:51:56",
        "channel_id": 1002093242621374594,
        "channel_name": "run-js-a-new-library-for-running-javascript-modules-in-python",
    },
    "THWRAC": {
        "title": "I Can't Believe It's Not Real Data! An Introduction into Synthetic Data",
        "youtube_url": "https://youtu.be/TZOA_wMHiPw",
        "content_warnings": None,
        "video_start_time": "10:12:10",
        "channel_id": 1002093243468615771,
        "channel_name": "i-can-t-believe-it-s-not-real-data-an-introduction-into-synthetic-data",
    },
    "DSRRMX": {
        "title": "Simplicity and Fun: Learning with CircuitPython",
        "youtube_url": "https://youtu.be/Wp9pK_ndh4g",
        "content_warnings": None,
        "video_start_time": "9:21:10",
        "channel_id": 1002093244093571082,
        "channel_name": "simplicity-and-fun-learning-with-circuitpython",
    },
    "RXLTKZ": {
        "title": "Automating Excel with Python",
        "youtube_url": "https://youtu.be/ZUEziLUbTIU",
        "content_warnings": None,
        "video_start_time": "12:35:47",
        "channel_id": 1002093244684963881,
        "channel_name": "automating-excel-with-python",
    },
    "EKYFK7": {
        "title": "Processing Large Data with Pandas",
        "youtube_url": "https://youtu.be/a6Ej3u01vFQ",
        "content_warnings": None,
        "video_start_time": "9:58:48",
        "channel_id": 1002093246085873714,
        "channel_name": "processing-large-data-with-pandas",
    },
    "VBHM8G": {
        "title": "What Is a Reasonable Percentage for Code Coverage and Why Is It 100%?",
        "youtube_url": "https://youtu.be/C1hO0naoU8I",
        "content_warnings": None,
        "video_start_time": "10:50:10",
        "channel_id": 1002093247247687690,
        "channel_name": "what-is-a-reasonable-percentage-for-code-coverage-and-why-is-it-100",
    },
    "TWC3VV": {
        "title": "Build Your First Anomaly Detector in Power BI Using PyCaret",
        "youtube_url": "https://youtu.be/Wy-LAJcakD8",
        "content_warnings": None,
        "video_start_time": "13:15:00",
        "channel_id": None,
        "channel_name": None,
    },
    "3AQ8XP": {
        "title": "Jupyter for DevOps",
        "youtube_url": "https://youtu.be/1oR0mfon1AM",
        "content_warnings": None,
        "video_start_time": "12:56:14",
        "channel_id": 1002093248271110225,
        "channel_name": "jupyter-for-devops",
    },
    "AKNMAS": {
        "title": "PyOhio 2022 Opening Remarks",
        "youtube_url": "https://youtu.be/3TbeMvlFB9E",
        "content_warnings": None,
        "video_start_time": "9:00:00",
        "channel_id": None,
        "channel_name": None,
    },
    "VPHVKC": {
        "title": "I Have to Confess, I Still Love Pandas",
        "youtube_url": "https://youtu.be/gFGlXvFemVk",
        "content_warnings": None,
        "video_start_time": "9:45:00",
        "channel_id": None,
        "channel_name": None,
    },
    "GDKLTP": {
        "title": "Baby Steps Towards Your First FastAPI App",
        "youtube_url": "https://youtu.be/q4BUHmPt7oY",
        "content_warnings": None,
        "video_start_time": "15:15:00",
        "channel_id": 1002093249160298577,
        "channel_name": "baby-steps-towards-your-first-fastapi-app",
    },
    "YQWKWN": {
        "title": "make python devex: Towards Clone to Red-Green-Refactor in One Command with a 45+-Year-Old Tool",
        "youtube_url": "https://youtu.be/WTsiO3brQwE",
        "content_warnings": None,
        "video_start_time": "11:28:38",
        "channel_id": 1002093249923657728,
        "channel_name": "make-python-devex-towards-clone-to-red-green-refactor-in-one-command-with-a-45-year-old-tool",
    },
    "QTSB88": {
        "title": "Bootstrapping Your Local Python Environment",
        "youtube_url": "https://youtu.be/qPT7X6VYqo8",
        "content_warnings": None,
        "video_start_time": "11:15:00",
        "channel_id": 1002093250586361856,
        "channel_name": "bootstrapping-your-local-python-environment",
    },
    "UEU39Y": {
        "title": "Go 3D with Plotly",
        "youtube_url": "https://youtu.be/fwRTohFjq5w",
        "content_warnings": None,
        "video_start_time": "13:44:41",
        "channel_id": None,
        "channel_name": None,
    },
    "HAP8VZ": {
        "title": "Remote Collaboration: How to Build Human Connection Across Pixels",
        "youtube_url": "https://youtu.be/g4e-pTxyHsM",
        "content_warnings": None,
        "video_start_time": "11:53:46",
        "channel_id": 1002093252041777233,
        "channel_name": "remote-collaboration-how-to-build-human-connection-across-pixels",
    },
    "N9XS8Y": {
        "title": "Comprehending Comprehensions",
        "youtube_url": "https://youtu.be/ScsElLE_Pak",
        "content_warnings": None,
        "video_start_time": "13:29:58",
        "channel_id": 1002093252796751872,
        "channel_name": "comprehending-comprehensions",
    },
    "AZAKUZ": {
        "title": "Exploring Open Source Sprint Data via a Python Plotly Dashboard",
        "youtube_url": "https://youtu.be/kY4XiFCf_B4",
        "content_warnings": None,
        "video_start_time": "14:35:00",
        "channel_id": 1002093253253922887,
        "channel_name": "exploring-open-source-sprint-data-via-a-python-plotly-dashboard",
    },
    "NV7NLB": {
        "title": "Colors and Chords",
        "youtube_url": "https://youtu.be/cSuSVJz7AP4",
        "content_warnings": None,
        "video_start_time": "9:31:25",
        "channel_id": 1002093254436728892,
        "channel_name": "colors-and-chords",
    },
    "SJWBN9": {
        "title": "Paginated APIs x Python",
        "youtube_url": "https://youtu.be/RCQhchesRt0",
        "content_warnings": None,
        "video_start_time": "15:36:47",
        "channel_id": None,
        "channel_name": None,
    },
    "ULKKUE": {
        "title": "Another Look at Python Types",
        "youtube_url": "https://youtu.be/Z3BcBnQb3eI",
        "content_warnings": None,
        "video_start_time": "13:55:00",
        "channel_id": 1002093255422386187,
        "channel_name": "another-look-at-python-types",
    },
    "H8L7HD": {
        "title": "OpenAPI Driven Development",
        "youtube_url": "https://youtu.be/VhRonVCkoNk",
        "content_warnings": None,
        "video_start_time": "15:42:24",
        "channel_id": 1002093256567431258,
        "channel_name": "openapi-driven-development",
    },
    "Z7X9MQ": {
        "title": "Paving an Easier Path to Your Next Tech Job",
        "youtube_url": "https://youtu.be/S39lZ7Ztw5U",
        "content_warnings": None,
        "video_start_time": "11:42:12",
        "channel_id": 1002093257305624616,
        "channel_name": "paving-an-easier-path-to-your-next-tech-job",
    },
    "98ZPHF": {
        "title": "Flappy Bird AI!",
        "youtube_url": "https://youtu.be/2Cm8AcCg2aI",
        "content_warnings": None,
        "video_start_time": "9:04:00",
        "channel_id": None,
        "channel_name": None,
    },
    "TMCZSL": {
        "title": "Deploy a Python API to the Cloud, Fast!",
        "youtube_url": "https://youtu.be/jD63M9y00m8",
        "content_warnings": None,
        "video_start_time": "15:26:44",
        "channel_id": None,
        "channel_name": None,
    },
    "BRXPVT": {
        "title": "Your Python Multi-Tool: Four Built-Ins and a Module",
        "youtube_url": "https://youtu.be/1BHVDsB57yQ",
        "content_warnings": None,
        "video_start_time": "13:24:49",
        "channel_id": 1002093257787981915,
        "channel_name": "your-python-multi-tool-four-built-ins-and-a-module",
    },
    "KGPRLM": {
        "title": "Advanced Typing: TypeVars, Generics, and Protocols",
        "youtube_url": "https://youtu.be/oJd6lhF0JbI",
        "content_warnings": None,
        "video_start_time": "14:06:39",
        "channel_id": 1002093258622631947,
        "channel_name": "advanced-typing-typevars-generics-and-protocols",
    },
    "YGLZWX": {
        "title": "A Quickstart to Web Testing with Playwright",
        "youtube_url": "https://youtu.be/_tAhD-OCuN8",
        "content_warnings": None,
        "video_start_time": "10:41:12",
        "channel_id": None,
        "channel_name": None,
    },
    "ZXVC8B": {
        "title": "Building a Faster NetworkX-Like Library Using GraphBLAS",
        "youtube_url": "https://youtu.be/lVkkBj6m9K0",
        "content_warnings": None,
        "video_start_time": "14:56:59",
        "channel_id": 1002093260346499153,
        "channel_name": "building-a-faster-networkx-like-library-using-graphblas",
    },
    "QYNCQC": {
        "title": "Introducing Automated Machine Learning with Python and Azure",
        "youtube_url": "https://youtu.be/4JI5ezqmYJQ",
        "content_warnings": None,
        "video_start_time": "14:47:11",
        "channel_id": 1002093261118251018,
        "channel_name": "introducing-automated-machine-learning-with-python-and-azure",
    },
    "BSNAWP": {
        "title": "More ORM Than Good: Stop Not Writing SQL",
        "youtube_url": "https://youtu.be/jeyr2brQM7k",
        "content_warnings": None,
        "video_start_time": "10:56:24",
        "channel_id": 1002093262024224808,
        "channel_name": "more-orm-than-good-stop-not-writing-sql",
    },
    "BD8VVJ": {
        "title": "Add RSS to My Website with Python? Yes!",
        "youtube_url": "https://youtu.be/QXuZNAijplI",
        "content_warnings": None,
        "video_start_time": "12:30:25",
        "channel_id": 1002093262779191337,
        "channel_name": "add-rss-to-my-website-with-python-yes",
    },
    "KWLY7G": {
        "title": "Visual Studio Code: The Ultimate Python Developer Environment",
        "youtube_url": "https://youtu.be/4O3Z49T8xLM",
        "content_warnings": None,
        "video_start_time": "14:20:17",
        "channel_id": 1002093263534166076,
        "channel_name": "visual-studio-code-the-ultimate-python-developer-environment",
    },
    "8SEMKX": {
        "title": "That Belongs in a Table: Migrating Data from JSON to SQL",
        "youtube_url": "https://youtu.be/mmpuAWNJwx8",
        "content_warnings": None,
        "video_start_time": "11:00:16",
        "channel_id": None,
        "channel_name": None,
    },
    "TCJAEP": {
        "title": "Beyond Velocity: 3 Metrics for Engineering Team Success",
        "youtube_url": "https://youtu.be/-qpCJqQByx0",
        "content_warnings": None,
        "video_start_time": "13:06:23",
        "channel_id": 1002093264473690213,
        "channel_name": "beyond-velocity-3-metrics-for-engineering-team-success",
    },
    "PCFFBK": {
        "title": "PyOhio 2022 Closing Remarks",
        "youtube_url": "https://youtu.be/Ci_HEdBSOMU",
        "content_warnings": None,
        "video_start_time": "15:58:43",
        "channel_id": None,
        "channel_name": None,
    },
}
