code: DCZDL9
content_warnings: null
description: '<p><strong>We regret to announce that Sameer was unable to attend PyOhio
  and that this session has been canceled.</strong> Sorry, folks!</p>

  <hr />

  <p>In this session, we will explore techniques for building resilient applications
  that can gracefully handle failures and ensure high availability. Specifically,
  we will focus on implementing circuit breakers and retry mechanisms using FastAPI.
  By the end of this talk, attendees will understand the principles behind these patterns
  and see a live demonstration of how to implement them in a FastAPI application.</p>'
discord_channel_id: ''
duration: 30
end_time: '2024-07-27T11:30:00-04:00'
qna: true
qna_channel: Canceled
room: Orchid Ballroom East
slug: canceled-building-resilient-applications-with-circuit-breakers
speakers:
- avatar: https://pretalx.com/media/avatars/HMNDYW_D9Kheqe.jpeg
  code: HMNDYW
  name: Sameer Shukla
  slug: sameer-shukla
start_time: '2024-07-27T11:00:00-04:00'
stream_timestamp: ''
title: 'Canceled: Building Resilient Applications with Circuit Breakers and Retries
  Using FastAPI'
type: 30 Minute Talk
youtube_url: null
